name: chichvirus
description: A Flutter game

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.17.6 <3.0.0'

dependencies:
  dio: ^4.0.6
  equatable: ^2.0.5
  firebase_auth: ^3.9.0
  firebase_core: ^1.22.0
  firebase_database: ^9.1.5
  flame: ^1.3.0
  flame_behaviors: ^0.1.1
  flame_bloc: ^1.7.0
  flame_mini_sprite: ^0.0.1+1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.1
  flutter_hooks: ^0.18.5+1
  fpdart: ^0.2.0
  go_router: ^5.0.1
  hooks_riverpod: ^1.0.4
  http: ^0.13.5
  mini_sprite: ^0.0.2
  near_api_flutter: ^0.0.11-alpha
  shared_preferences: ^2.0.15

dev_dependencies:
  flutter_lints: 2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  fonts:
    - family: Minecraft
      fonts:
        - asset: assets/fonts/Minecraft.ttf
  assets:
    - config/
